"""Deutsche Namen fuer die Geraeteeigenschaften von Eufy.

Die Bibliothek liefert zu jeder Eigenschaft ein englisches Label
("Motion Detection Sensitivity"). Hier steht die deutsche Fassung - so,
wie man es in der Eufy-App auch lesen wuerde, nicht Wort fuer Wort.

Fehlt eine Eigenschaft, bleibt das englische Label; nichts geht kaputt.
Die Entity-IDs aendern sich durch eine Umbenennung nicht, die haengen
an der unique_id.
"""

from __future__ import annotations

# Eigenschaft -> deutscher Name
NAMEN: dict[str, str] = {
    # ---- Kamera allgemein ------------------------------------------------
    "enabled": "Kamera aktiv",
    "statusLed": "Status-LED",
    "watermark": "Wasserzeichen",
    "imageMirrored": "Bild gespiegelt",
    "flickerAdjustment": "Flimmerausgleich",
    "videoHdr": "HDR",
    "videoWdr": "WDR",
    "videoDistortionCorrection": "Verzerrungskorrektur",
    "videoStreamingQuality": "Qualitaet Livebild",
    "videoRecordingQuality": "Qualitaet Aufnahme",
    "videoRingRecord": "Aufnehmen waehrend Livebild nach Klingeln",
    "videoTypeStoreToNAS": "Auf NAS speichern",
    "rtspStream": "RTSP-Stream",
    "rtspStreamUrl": "RTSP-Adresse",
    "microphone": "Mikrofon",
    "speaker": "Lautsprecher",
    "speakerVolume": "Lautstaerke Lautsprecher",
    "audioRecording": "Tonaufnahme",
    "autoCalibration": "Automatische Kalibrierung",
    "rotationSpeed": "Schwenkgeschwindigkeit",
    "defaultAngle": "Standardposition",
    "defaultAngleIdleTime": "Zurueck zur Standardposition nach",
    "dualCamWatchViewMode": "Ansicht Doppelkamera",
    "powerSave": "Energiesparen",
    "powerSource": "Stromversorgung",
    "powerWorkingMode": "Betriebsmodus Strom",
    "recordingClipLength": "Aufnahmedauer",
    "recordingRetriggerInterval": "Pause zwischen Aufnahmen",
    "recordingEndClipMotionStops": "Aufnahme beenden, wenn Bewegung endet",
    "continuousRecording": "Daueraufnahme",
    "continuousRecordingType": "Art der Daueraufnahme",
    "picture": "Letztes Ereignisbild",
    "pictureUrl": "Adresse Ereignisbild",
    "deviceSnooze": "Stummschalten",
    "snoozeMotion": "Bewegung stummgeschaltet",
    "snoozeHomebase": "HomeBase stummgeschaltet",
    "snoozeStartChime": "Klingel stummgeschaltet",
    "snoozeStartTime": "Stummschaltung seit",
    "snoozeTime": "Stummschaltung Dauer",
    "state": "Zustand",
    "name": "Name",
    "model": "Modell",
    "type": "Typ",
    "serialNumber": "Seriennummer",
    "stationSerialNumber": "Seriennummer Station",
    "hardwareVersion": "Hardware-Version",
    "softwareVersion": "Firmware",
    "macAddress": "MAC-Adresse",
    "lanIpAddress": "IP-Adresse",
    "wifiRssi": "WLAN-Signal (dBm)",
    "wifiSignalLevel": "WLAN-Signalstaerke",
    "timeFormat": "Zeitformat",
    "timeZone": "Zeitzone",
    # ---- Akku -------------------------------------------------------------
    "battery": "Akku",
    "batteryLow": "Akku schwach",
    "batteryIsCharging": "Wird geladen",
    "chargingStatus": "Ladezustand",
    "batteryTemperature": "Akkutemperatur",
    "batteryUsageLastWeek": "Akkuverbrauch letzte Woche",
    "batteryFullyChargedAlert": "Meldung Akku voll",
    "lowBatteryAlert": "Meldung Akku schwach",
    "lastChargingDays": "Tage seit letzter Ladung",
    "lastChargingTotalEvents": "Ereignisse seit letzter Ladung",
    "lastChargingRecordedEvents": "Aufnahmen seit letzter Ladung",
    "lastChargingFalseEvents": "Fehlausloesungen seit letzter Ladung",
    "highTemperatureAlert": "Meldung zu heiss",
    "lowTemperatureAlert": "Meldung zu kalt",
    # ---- Nachtsicht und Licht -------------------------------------------
    "nightvision": "Nachtsicht",
    "autoNightvision": "Automatische Nachtsicht",
    "nightvisionOptimization": "Nachtsicht optimieren",
    "nightvisionOptimizationSide": "Nachtsicht optimieren Seite",
    "videoColorNightvision": "Farbige Nachtsicht",
    "videoNightvisionImageAdjustment": "Bildanpassung Nachtsicht",
    "light": "Licht",
    "lightSettingsEnable": "Licht aktiv",
    "lightSettingsBrightnessManual": "Helligkeit manuell",
    "lightSettingsBrightnessMotion": "Helligkeit bei Bewegung",
    "lightSettingsBrightnessSchedule": "Helligkeit nach Zeitplan",
    "lightSettingsColorTemperatureManual": "Farbtemperatur manuell",
    "lightSettingsColorTemperatureMotion": "Farbtemperatur bei Bewegung",
    "lightSettingsColorTemperatureSchedule": "Farbtemperatur nach Zeitplan",
    "lightSettingsMotionTriggered": "Licht bei Bewegung",
    "lightSettingsMotionTriggeredDistance": "Licht bei Bewegung Reichweite",
    "lightSettingsMotionTriggeredTimer": "Licht bei Bewegung Dauer",
    "lightSettingsMotionActivationMode": "Licht bei Bewegung Ausloeser",
    "lightSettingsManualLightingActiveMode": "Lichtmodus manuell",
    "lightSettingsMotionLightingActiveMode": "Lichtmodus bei Bewegung",
    "lightSettingsScheduleLightingActiveMode": "Lichtmodus nach Zeitplan",
    "lightSettingsManualDailyLighting": "Weisslicht manuell",
    "lightSettingsMotionDailyLighting": "Weisslicht bei Bewegung",
    "lightSettingsScheduleDailyLighting": "Weisslicht nach Zeitplan",
    "lightSettingsManualColoredLighting": "Farblicht manuell",
    "lightSettingsMotionColoredLighting": "Farblicht bei Bewegung",
    "lightSettingsScheduleColoredLighting": "Farblicht nach Zeitplan",
    "lightSettingsManualDynamicLighting": "Lichteffekt manuell",
    "lightSettingsMotionDynamicLighting": "Lichteffekt bei Bewegung",
    "lightSettingsScheduleDynamicLighting": "Lichteffekt nach Zeitplan",
    "lightSettingsColoredLightingColors": "Farben Farblicht",
    "lightSettingsDynamicLightingThemes": "Lichteffekte",
    "interiorBrightness": "Innenhelligkeit",
    "interiorBrightnessDuration": "Innenhelligkeit Dauer",
    # ---- Bewegungserkennung -----------------------------------------------
    "motionDetection": "Bewegungserkennung",
    "motionDetected": "Bewegung",
    "personDetected": "Person",
    "petDetected": "Tier",
    "dogDetected": "Hund",
    "dogLickDetected": "Hund leckt",
    "dogPoopDetected": "Hund macht Haufen",
    "vehicleDetected": "Fahrzeug",
    "soundDetected": "Geraeusch",
    "cryingDetected": "Weinen",
    "radarMotionDetected": "Bewegung (Radar)",
    "strangerPersonDetected": "Unbekannte Person",
    "identityPersonDetected": "Bekannte Person",
    "personName": "Erkannte Person",
    "motionSensorPirEvent": "Bewegungssensor ausgeloest",
    "motionDetectionType": "Erkennungsart",
    "motionDetectionTypeHuman": "Erkennen: Personen",
    "motionDetectionTypeHumanRecognition": "Erkennen: Gesichter",
    "motionDetectionTypePet": "Erkennen: Tiere",
    "motionDetectionTypeVehicle": "Erkennen: Fahrzeuge",
    "motionDetectionTypeAllOtherMotions": "Erkennen: alle anderen Bewegungen",
    "motionDetectionSensitivity": "Empfindlichkeit",
    "motionDetectionSensitivityMode": "Empfindlichkeit Modus",
    "motionDetectionSensitivityStandard": "Empfindlichkeit Standard",
    "motionDetectionSensitivityAdvancedA": "Empfindlichkeit Zone A",
    "motionDetectionSensitivityAdvancedB": "Empfindlichkeit Zone B",
    "motionDetectionSensitivityAdvancedC": "Empfindlichkeit Zone C",
    "motionDetectionSensitivityAdvancedD": "Empfindlichkeit Zone D",
    "motionDetectionSensitivityAdvancedE": "Empfindlichkeit Zone E",
    "motionDetectionSensitivityAdvancedF": "Empfindlichkeit Zone F",
    "motionDetectionSensitivityAdvancedG": "Empfindlichkeit Zone G",
    "motionDetectionSensitivityAdvancedH": "Empfindlichkeit Zone H",
    "motionDetectionRange": "Erkennungsreichweite",
    "motionDetectionRangeStandardSensitivity": "Reichweite Standard",
    "motionDetectionRangeAdvancedLeftSensitivity": "Reichweite links",
    "motionDetectionRangeAdvancedMiddleSensitivity": "Reichweite Mitte",
    "motionDetectionRangeAdvancedRightSensitivity": "Reichweite rechts",
    "motionDetectionTestMode": "Testmodus Bewegungserkennung",
    "motionZone": "Erkennungsbereich",
    "motionTracking": "Bewegung verfolgen",
    "motionTrackingSensitivity": "Verfolgung Empfindlichkeit",
    "motionAutoCruise": "Automatisches Schwenken",
    "motionOutOfViewDetection": "Erkennung ausserhalb des Bildes",
    "motionActivatedPrompt": "Ansage bei Bewegung",
    "continuousTrackingTime": "Verfolgung Dauer",
    "crossCameraTracking": "Ueber mehrere Kameras verfolgen",
    "crossTrackingCameraList": "Kameras fuer Verfolgung",
    "crossTrackingGroupList": "Gruppen fuer Verfolgung",
    "trackingAssistance": "Verfolgungshilfe",
    "petDetection": "Tiererkennung",
    "soundDetection": "Geraeuscherkennung",
    "soundDetectionType": "Geraeuscherkennung Art",
    "soundDetectionSensitivity": "Geraeuscherkennung Empfindlichkeit",
    "soundDetectionRoundLook": "Bei Geraeusch umsehen",
    "loiteringDetection": "Herumlungern erkennen",
    "loiteringDetectionRange": "Herumlungern Reichweite",
    "loiteringDetectionLength": "Herumlungern ab Dauer",
    "loiteringCustomResponsePhoneNotification": "Herumlungern: Handy-Meldung",
    "loiteringCustomResponseHomeBaseNotification": "Herumlungern: HomeBase-Meldung",
    "loiteringCustomResponseAutoVoiceResponse": "Herumlungern: Sprachansage",
    "loiteringCustomResponseAutoVoiceResponseVoice": "Herumlungern: Ansagetext",
    "loiteringCustomResponseTimeFrom": "Herumlungern: von",
    "loiteringCustomResponseTimeTo": "Herumlungern: bis",
    "someoneLoitering": "Jemand lungert herum",
    "someoneGoing": "Jemand geht",
    "leavingDetection": "Weggehen erkennen",
    "leavingReactionNotification": "Weggehen: Meldung",
    "leavingReactionStartTime": "Weggehen: von",
    "leavingReactionEndTime": "Weggehen: bis",
    "detectionStatisticsWorkingDays": "Statistik: Tage in Betrieb",
    "detectionStatisticsDetectedEvents": "Statistik: erkannte Ereignisse",
    "detectionStatisticsRecordedEvents": "Statistik: aufgenommene Ereignisse",
    "antitheftDetection": "Diebstahlschutz",
    # ---- Benachrichtigungen ----------------------------------------------
    "notification": "Benachrichtigungen",
    "notificationType": "Art der Benachrichtigung",
    "notificationMotion": "Melden: Bewegung",
    "notificationPerson": "Melden: Person",
    "notificationPet": "Melden: Tier",
    "notificationVehicle": "Melden: Fahrzeug",
    "notificationAllOtherMotion": "Melden: alle anderen Bewegungen",
    "notificationAllSound": "Melden: Geraeusch",
    "notificationCrying": "Melden: Weinen",
    "notificationRing": "Melden: Klingeln",
    "notificationRadarDetector": "Melden: Radar-Bewegung",
    "notificationIntervalTime": "Pause zwischen Meldungen",
    "notificationSwitchModeApp": "Melden: Moduswechsel per App",
    "notificationSwitchModeGeofence": "Melden: Moduswechsel per Geofence",
    "notificationSwitchModeSchedule": "Melden: Moduswechsel per Zeitplan",
    "notificationSwitchModeKeypad": "Melden: Moduswechsel per Tastenfeld",
    "notificationStartAlarmDelay": "Melden: Alarmverzoegerung laeuft",
    # ---- Klingel ----------------------------------------------------------
    "ringing": "Es klingelt",
    "ringtoneVolume": "Klingellautstaerke",
    "chimeIndoor": "Innenklingel",
    "chimeHomebase": "HomeBase-Klingel",
    "chimeHomebaseRingtoneType": "HomeBase-Klingelton",
    "chimeHomebaseRingtoneVolume": "HomeBase-Klingellautstaerke",
    "ringAutoResponse": "Automatische Antwort bei Klingeln",
    "ringAutoResponseVoiceResponse": "Automatische Antwort: Ansage",
    "ringAutoResponseVoiceResponseVoice": "Automatische Antwort: Ansagetext",
    "ringAutoResponseTimeFrom": "Automatische Antwort: von",
    "ringAutoResponseTimeTo": "Automatische Antwort: bis",
    "deliveryGuard": "Paketwaechter",
    "deliveryGuardPackageGuarding": "Paketwaechter: Paket bewachen",
    "deliveryGuardPackageGuardingVoiceResponseVoice": "Paketwaechter: Ansagetext",
    "deliveryGuardPackageGuardingActivatedTimeFrom": "Paketwaechter: von",
    "deliveryGuardPackageGuardingActivatedTimeTo": "Paketwaechter: bis",
    "deliveryGuardPackageLiveCheckAssistance": "Paketwaechter: Livebild-Hilfe",
    "deliveryGuardUncollectedPackageAlert": "Paketwaechter: Meldung nicht abgeholt",
    "deliveryGuardUncollectedPackageAlertTimeToCheck": "Paketwaechter: Pruefzeit",
    "packageDelivered": "Paket geliefert",
    "packageTaken": "Paket abgeholt",
    "packageStranded": "Paket liegt noch",
    "isDeliveryDenied": "Lieferung abgelehnt",
    "deliveries": "Lieferungen",
    # ---- Station / HomeBase / Alarm --------------------------------------
    "guardMode": "Modus",
    "currentMode": "Aktueller Modus",
    "alarm": "Alarm",
    "alarmType": "Alarmart",
    "alarmArmed": "Alarm scharf",
    "alarmArmDelay": "Verzoegerung beim Scharfschalten",
    "alarmDelay": "Alarmverzoegerung",
    "alarmDelayType": "Art der Alarmverzoegerung",
    "alarmVolume": "Alarmlautstaerke",
    "alarmTone": "Alarmton",
    "autoEndAlarm": "Alarm automatisch beenden",
    "turnOffAlarmWithButton": "Alarm per Taste beenden",
    "promptVolume": "Lautstaerke Ansagen",
    "switchModeWithAccessCode": "Moduswechsel mit Code",
    "tamperAlarm": "Sabotagealarm",
    "tamperingAlert": "Meldung Sabotage",
    "sdStatus": "Speicherkarte Status",
    "sdCapacity": "Speicherkarte Groesse",
    "sdCapacityAvailable": "Speicherkarte frei",
    "storageInfoEmmc": "Speicher intern",
    "storageInfoHdd": "Speicher Festplatte",
    "storageInfoSdCard": "Speicher Karte",
    "cellularSignal": "Mobilfunksignal",
    "cellularSignalLevel": "Mobilfunk Signalstaerke",
    "cellularRSSI": "Mobilfunk RSSI",
    "cellularBand": "Mobilfunkband",
    "cellularIMEI": "IMEI",
    "cellularICCID": "ICCID",
    "findPhone": "Handy finden",
    "locationAddress": "Standort Adresse",
    "locationCoordinates": "Standort Koordinaten",
    "locationLastUpdate": "Standort zuletzt aktualisiert",
    "trackerType": "Tracker-Art",
    "leftBehindAlarm": "Meldung Vergessen",
    # ---- Sensoren ---------------------------------------------------------
    "sensorOpen": "Offen",
    "sensorChangeTime": "Zuletzt geaendert",
    "deviceOpen": "Offen",
    "door1Open": "Tuer 1 offen",
    "door2Open": "Tuer 2 offen",
    "doorControlWarning": "Warnung Tuersteuerung",
    "leftOpenAlarm": "Meldung Offen gelassen",
    "leftOpenAlarmDuration": "Offen gelassen ab Dauer",
    "longTimeNotCloseAlert": "Meldung lange nicht geschlossen",
    "lidStuckAlert": "Meldung Deckel klemmt",
    "pinIncorrectAlert": "Meldung PIN falsch",
    "shakeAlert": "Meldung Erschuetterung",
    "shakeAlertEvent": "Erschuetterung",
    "911Alert": "Notruf-Alarm",
    "911AlertEvent": "Notruf ausgeloest",
    "jammedAlert": "Meldung blockiert",
    # ---- Schloss ----------------------------------------------------------
    "locked": "Verriegelt",
    "lockStatus": "Schlossstatus",
    "lockEventOrigin": "Ausloeser letzte Aktion",
    "autoLock": "Automatisch verriegeln",
    "autoLockTimer": "Automatisch verriegeln nach",
    "autoLockSchedule": "Automatisch verriegeln nach Zeitplan",
    "autoLockScheduleStartTime": "Automatisch verriegeln: von",
    "autoLockScheduleEndTime": "Automatisch verriegeln: bis",
    "oneTouchLocking": "Verriegeln per Tastendruck",
    "dualUnlock": "Doppelte Entriegelung",
    "remoteUnlock": "Fernentriegelung",
    "remoteUnlockMasterPIN": "Fernentriegelung mit Master-PIN",
    "hasMasterPin": "Master-PIN vorhanden",
    "scramblePasscode": "Code verschleiern",
    "wrongTryProtection": "Schutz vor Fehlversuchen",
    "wrongTryAttempts": "Fehlversuche bis Sperre",
    "wrongTryLockdownTime": "Sperrdauer nach Fehlversuchen",
    "wrongTryProtectAlert": "Meldung Fehlversuche",
    "openMethod": "Art der Oeffnung",
    "openedByType": "Geoeffnet per",
    "openedByName": "Geoeffnet von",
    "beepVolume": "Lautstaerke Piepton",
    "chirpTone": "Signalton",
    "chirpVolume": "Lautstaerke Signalton",
    "sound": "Ton",
    "notificationLocked": "Melden: verriegelt",
    "notificationUnlocked": "Melden: entriegelt",
    "notificationDualLock": "Melden: doppelt verriegelt",
    "notificationDualUnlock": "Melden: doppelt entriegelt",
    "notificationJammed": "Melden: blockiert",
    "notificationWrongTryProtect": "Melden: Fehlversuche",
    "notificationUnlockByApp": "Melden: entriegelt per App",
    "notificationUnlockByKey": "Melden: entriegelt per Schluessel",
    "notificationUnlockByPIN": "Melden: entriegelt per PIN",
    "notificationUnlockByFingerprint": "Melden: entriegelt per Fingerabdruck",
}

# Auswahlwerte -> deutsch. Gilt fuer alle Auswahllisten; was hier nicht
# steht, bleibt wie geliefert.
WERTE: dict[str, str] = {
    "Off": "Aus",
    "On": "An",
    "Auto": "Automatisch",
    "Low": "Niedrig",
    "Medium": "Mittel",
    "High": "Hoch",
    "Lowest": "Sehr niedrig",
    "Highest": "Sehr hoch",
    "Standard": "Standard",
    "Advanced": "Erweitert",
    "Full HD": "Full HD",
    "2K HD": "2K",
    "4K": "4K",
    "Human": "Personen",
    "Humans": "Personen",
    "Person": "Personen",
    "Pet": "Tiere",
    "Pets": "Tiere",
    "Vehicle": "Fahrzeuge",
    "Vehicles": "Fahrzeuge",
    "All motions": "Alle Bewegungen",
    "All Motions": "Alle Bewegungen",
    "All other motions": "Alle anderen Bewegungen",
    "Human and Pet": "Personen und Tiere",
    "Human and Vehicle": "Personen und Fahrzeuge",
    "Pet and Vehicle": "Tiere und Fahrzeuge",
    "Human, Pet and Vehicle": "Personen, Tiere und Fahrzeuge",
    "Most efficient": "Nur Text",
    "Include thumbnail": "Mit Vorschaubild",
    "Full effect": "Vollstaendig",
    "Optimal Battery Life": "Lange Akkulaufzeit",
    "Optimal Surveillance": "Beste Ueberwachung",
    "Custom Recording": "Eigene Einstellung",
    "Plugged In": "Netzbetrieb",
    "Battery": "Akku",
    "Solar Panel": "Solar",
    "B&W": "Schwarzweiss",
    "Spotlight": "Scheinwerfer",
    "Color": "Farbe",
    "Charging": "Laedt",
    "Not Charging": "Laedt nicht",
    "Fully Charged": "Voll geladen",
    "12 hours": "12 Stunden",
    "24 hours": "24 Stunden",
    "Always": "Immer",
    "Schedule": "Zeitplan",
    "Motion": "Bewegung",
    "Manual": "Manuell",
    "Weak": "Schwach",
    "Normal": "Normal",
    "Strong": "Stark",
    "Excellent": "Sehr gut",
    "Good": "Gut",
    "Fair": "Maessig",
    "Poor": "Schlecht",
    "None": "Keine",
    "No Signal": "Kein Signal",
    "Left": "Links",
    "Right": "Rechts",
    "Both": "Beide",
    "Alarm sound 1": "Alarmton 1",
    "Alarm sound 2": "Alarmton 2",
    "Ok": "In Ordnung",
    "Not connected": "Nicht verbunden",
}


def name(prop: str, label: str | None) -> str:
    """Deutscher Name, sonst englisches Label, sonst aus dem Schluessel."""
    if prop in NAMEN:
        return NAMEN[prop]
    if label:
        return label
    out = ""
    for char in prop:
        if char.isupper() and out:
            out += " "
        out += char
    return out[:1].upper() + out[1:]


def wert(label: str) -> str:
    """Deutscher Auswahlwert, sonst wie geliefert."""
    return WERTE.get(label, label)
